[project]
name = "prefect-cluster"
version = "0.1.0"
description = "My own Prefect Cluster."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible>=13.3.0",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.5",
]
