---
- name: Configure Nomad server
  ansible.builtin.template:
    src: server.hcl.j2
    dest: "{{ nomad_config_dir }}/server.hcl"
    owner: nomad
    group: nomad
    mode: "0640"
  notify: Restart nomad

- name: Enable and start Nomad
  ansible.builtin.systemd_service:
    name: nomad
    state: started
    enabled: true
