---
- name: Show Python library paths
  community.general.python_requirements_info:

- name: Install pip
  ansible.builtin.apt:
    name:
      - python3-pip
    state: present
    update_cache: true
